version: "3.9"

networks:
  network_traefik:
    external: true
  network_mariadb:
    external: true
  network_nextcloud_internal:
    internal: true
    
services:

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: always
    networks:
      - network_traefik
      - network_mariadb
      - network_nextcloud_internal
    volumes:
      - ./datas/nextcloud:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.docker.network=network_traefik
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.nextcloud.middlewares=nc-rep,nc-header"
      - "traefik.http.middlewares.nc-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nc-rep.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-header.headers.frameDeny=true"
      - "traefik.http.middlewares.nc-header.headers.sslRedirect=true"
      - "traefik.http.middlewares.nc-header.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.nc-header.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nc-header.headers.stsPreload=true"
      - "traefik.http.middlewares.nc-header.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.nc-header.headers.referrerPolicy=same-origin"
      - "traefik.http.middlewares.nc-header.headers.browserXssFilter=true"
      - "traefik.http.middlewares.nc-header.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.nc-header.headers.customResponseHeaders.X-Robots-Tag=none"
      - "traefik.http.middlewares.nc-header.headers.customFrameOptionsValue=SAMEORIGIN"
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN_NAME}
      - TRUSTED_PROXIES=172.33.0.0/16
      - REDIS_HOST=nextcloud_redis


  nextcloud_redis:
    container_name: nextcloud_redis
    image: redis:latest
    restart: always
    networks:
      - network_nextcloud_internal
    volumes:
      - ./datas/redis:/var/lib/redis
      
